### PR TITLE
Bump README dependencies to new 0.3.0 version

### PR DESCRIPTION
**Pull request by paulojrp**

### CODE REVIEW

**Comment by nmldiegues** [comment]
@paulojrp please fork hf-0.3.X and  bump master to 0.4.0-SNAPSHOT
Then tag + release 0.3.0

**Comment by nmldiegues** [comment]
"Froze" hf-0.2.X development branch as it is no longer maintained.
@paulojrp please bump the API jars on Pulse hf branches to 0.3.0 as it should be a trivial non-breaking change from the client perspective

**Comment by paulojrp** [comment]
@nmldiegues I don't think that I have permissions for that :(

**Comment by nmldiegues** [comment]
I've done it. In the meantime we'll add Paulo to the feedzai organization

**Pull request merged**
