### PR TITLE
Refactor openml-utils 'utils' test package into com.feedzai.openml

### PR DESCRIPTION
**Pull request by pedrorijo91**
The test package should have also been renamed on #28 during resolution of issue #15 

Other changes include (can be seen individually in separated commits):

- optimize imports
- update copyright headers in all files

### CODE REVIEW

**Comment by nmldiegues** [comment]
@pedrorijo91  Your IDE is changing to Feedzai's copyright policy, which altered all the files (also on the commit of f3aae348ebb326c994fe128514a1c5eece05b78f) so please revert it on all files.

**Comment by pedrorijo91** [comment]
@nmldiegues should be fixed. See the PR description for the full set of changes

**Comment by pedrorijo91** [comment]
cherry-picking into hf-0.2.X

**Comment by pedrorijo91** [comment]
releasing v.0.2.1 with this change. will propagate to providers as soon as it's available

**Pull request merged**
