### PR TITLE
Add pitest mutation test plugin

### PR DESCRIPTION
**Pull request by pedrorijo91**
This is an WIP experiment, which consists in adding the [pitest mutation testing framework](http://pitest.org/) into the codebase.

# What is mutation testing?

Mutation testing may work as a better technique for validating the effectiveness of the existing tests. 

Our current approach (and the industry standard) has been to use LoC coverage (a few use alternative metrics like function coverage, branch coverage, statement coverage, and etc - more on the subject at https://blog.codacy.com/what-your-mother-didnt-tell-you-about-code-coverage-605253143936#9699). Nevertheless, (LoC) code coverage only measures how many lines of code have been executed during the test execution. This means it's possible to have 100% LoC coverage, and the tests may be "weak" as it may not assert the right properties (or the developer may even forget to assert something on the test). On the other hand, mutation testing changes (mutates) the source code and checks if the tests capture the behaviour change. A classic example is changing some `if` statement by reverting its condition:

```
public long factorial(int n) {
  if (n <= 1) {
    return 1;   
  } else {    
    return(n * factorial(n-1));  
  }
}
```

gets mutated into

```
public long factorial(int n) {
  if (n > 1) { // note the condition was mutated
    return 1;   
  } else {    
    return(n * factorial(n-1));  
  }
}
```
If no test fails after this change, then there's something to improve on the tests. By introducing this framework we hope to improve our tests and decrease the possible bugs.

Note that by its definition itself, mutation testing may be slow since it implies run the test suite after introducing each mutation (or group of mutations)

# PR structure

This PR is still WIP, and aims to bring the following changes:

- [x] Add pitest plugin
- [x] Add pitest phase to CI
- [x] Use framework report to improve the codebase 
- [x] Add documentation on README for developers wanting to contribute

# Did pitest found any code problem already?

Well, if it hadn't, this PR wouldn't exist :)

The first finding of pitest was that we have somehow redundant verifications on our codebase: https://github.com/feedzai/feedzai-openml/blob/master/openml-api/src/main/java/com/feedzai/openml/data/schema/DatasetSchema.java#L87-L95

While the lines 87-90 only check the indexes are sorted, the lines 92-95 implicitly check the indexes are sorted because it compares the list of indexes with the range `0 until indexes.size()`, a comparison that would fail if the indexes weren't sorted.

Another example caught: NumericFieldTypeTest is not testing boundary values at https://github.com/feedzai/feedzai-openml/blob/master/openml-api/src/test/java/com/feedzai/openml/provider/fieldtype/NumericFieldTypeTest.java#L65-L70

by mutating `if (parsedValue < this.minValue)` into `if (parsedValue <= this.minValue)` at https://github.com/feedzai/feedzai-openml/blob/master/openml-api/src/main/java/com/feedzai/openml/provider/descriptor/fieldtype/NumericFieldType.java#L164 , the tests still pass. Why are not ensuring the `minValue` is allowed on our tests? :)

Really sure more dangerous cases will appear in the report (hadn't the time to look at everything since some cases are still being reported even if they aren't very relevant - see `failing builds` topic bello)

# Implementation details

1. failing builds

It's possible to introduce a threshold for which the build phase would fail (useful for CI): http://pitest.org/quickstart/maven/#mutationthreshold

I would like to try 100% mutation testing coverage, but I'm not sure if possible, at least for now. I've seen a few reports complaining on `hashcode`/`equals`/`toString` methods not being properly tested, but I don't seem much value on that.

There's also a configuration to disable specific methods and classes that I need to try: 

- http://pitest.org/quickstart/maven/#excludedmethods 
- http://pitest.org/quickstart/maven/#excludedclasses
- http://pitest.org/quickstart/maven/#avoidcallsto

:warning: Still needs work (currently at 50% threshold) 

2. selected mutations

I'm starting by enabling [all mutations](http://pitest.org/quickstart/maven/#mutators), but may decrease the list of mutations if we get some irrelevant results.

3. multi module projects

The pitest framework has a problem dealing with multi module maven projects.
The solution [presented](http://pitest.org/quickstart/maven/#handling-projects-composed-of-mutiple-maven-modules-pitmp) is to rely on the [pitmp-maven-plugin](https://github.com/STAMP-project/pitmp-maven-plugin).

To execute the mutation test just use the following command on the project root (it's also possible to run in one of the submodules root):

`mvn org.pitest:pitest-maven:mutationCoverage`

and check the report on the `target` folder (inside a `pit-reports` folder)

4. run mutation testing over the last commit

There's a command to run the framework on recent changes, which will probably be used to run on CI, but I still need to have a better look: http://pitest.org/quickstart/maven/#scmmutationcoverage-goal

**Edit:** the referred configuration it seems to be an option to run mutation testing before commit/push, and not to run over a PR on CI, so it is not very useful for now

5. parallelism 

It is possible to configure the number of threads to use when mutation testing using the [threads configuration](http://pitest.org/quickstart/maven/#threads). By default uses a single thread.

In a very rough experiment on my mac (we can't even call it benchmark):

* 1 thread takes 42s
* 2 threads take 34s
* 4 threads take 34s
* 8 threads take 34s

6. incremental analysis

For very large codebases there's an *experimental* feature on pitest: [incremental analysis](http://pitest.org/quickstart/incremental_analysis/) which optimises the runs by tracking changes to the code and tests and storing the results from previous runs. But it doesn't seem a very safe option for now. Will only have a look at it if the mutation testing phase starts taking too long

# How to read PIT reports

Let's take as the base for the explanation the current top commit of this PR (https://github.com/feedzai/feedzai-openml/pull/33/commits/929f1d191efe5397f1b8a2b459c928aec4f4b7ca), and look into the `openml-api` submodule.

We first need to have the code compiled:

```
$ mvn clean install -DskipTests
```

Now we can run the mutation testing:

```
$ mvn org.pitest:pitest-maven:mutationCoverage
```

and this will generate a `feedzai-openml/openml-api/target/pit-reports` folder. Nested, there will be another folder whose name corresponds to the datetime the mutation test maven goal was run (for instance `201808232236` -> 2018/08/23 22h36m). Here's the report you should have generated: https://files.feedzai.com/index.php/s/Jy5iJQLCMeiPXEm

My advise is to open the `index.html` file, where you will be able to see the overall line coverage and mutation coverage scores, as well as the breakdown by package. Let's have a look at the package `com.feedzai.openml.provider.descriptor.fieldtype` and select the `NumericFieldType.java` since it has 100% line coverage and 77% mutation coverage.

You will see each line may have 1 of 5 different background colors:

- no background color (white): usually comments, fields, and other non-testable lines
- light green: code with line coverage but no mutation was generated by that line (the method was ignored on the mutation testing framework config)
- stronger green: code with mutation testing coverage that passed (all the generated mutations were detected by the test suite 👍)
- light red/pink: no line coverage for this line. This means no test goes through the line while executing
- stronger red/pink: code without mutation testing. This means at least one of the generated mutations was not detected by the test suite 👎

On the left of the line there's the line number, and in lines with mutations generated, there's a number (total number of mutations generated to that line). On hover, a popup will appear with details on the mutations, explaining the change introduced by the mutation, and if the mutation survived (👎) or was killed (👍)

On line 113 of `NumericFieldType.java` report, we can see that the mutation coverage is not ok. There were generated 7 mutations, and 4 of them survived:

```
1. range : changed conditional boundary → SURVIVED
2. range : Substituted 0 with 1 → SURVIVED
3. range : removed conditional - replaced comparison check with true → SURVIVED
4. range : removed call to com/google/common/base/Preconditions::checkArgument → SURVIVED
5. range : Substituted 1 with 0 → KILLED
6. range : negated conditional → KILLED
7. range : removed conditional - replaced comparison check with false → KILLED
```

How to find the problem? Well, typically the explanation is somehow intuitive. 

1. The first mutation changed the conditional boundary which typically means the comparison operator had the equality added/removed (`<=` mutated into `<`).
2. This mutation is not as obvious because we wonder where is the `0`, but (and I'm not 100% sure, but it was the info I found at the time) there is a specific test where the method is called with one of the arguments as 0 (probably the `minValue`) and it was replaced by 1.
3. The third mutation changed the boolean expression into a constant value `true`
4. The last survived mutation is all about removing the line itself.

This means we need to have better tests on which values are allowed for this method. The improvement was introduced on https://github.com/feedzai/feedzai-openml/pull/34/files#diff-e49ec2f12a587bdb6dcc4aa89ffb357b

Most of the surviving mutations of this project are similar to these 4 examples: boolean expressions replaced by constant, deleted lines, boundaries changed.

### CODE REVIEW

**Comment by rfer** [comment]
This is awesome! Looking forward to see how this goes!

**Comment by nmldiegues** [comment]
@pedrorijo91 Can you document a simple example of:
 * this is the output of the plugin
 * this "???" means it's great
 * this "???" means you need to take action
 * and the action here would be "???"

**Comment by pedrorijo91** [comment]
Will do @nmldiegues. Been digging into the reports and making some fixes (#34). Will add some example(s) here soon

**Comment by pedrorijo91** [comment]
I've edited the PR description to contain the basic overview on how to read PIT reports @nmldiegues. I think it provides the general approach. 

So, I would say this work of mutation testing is ready to be fully reviewed (#33 and #34), and can already be merged (cc @henriquevcosta @rfer in case you are also interested in having a look). 
There are 2 issues I've found on the setup, which do not block this and that waiting for the maintainer to get back:

- pitmp mixing reports of different modules (https://github.com/STAMP-project/pitmp-maven-plugin/issues/17)
- pitmp is not using the latest PIT version (which solves https://github.com/hcoles/pitest/issues/497). I started working on the bumping, but got kinda blocked (https://github.com/STAMP-project/pitmp-maven-plugin/issues/16) and will try to find some time to dig into it soon

**Comment by pedrorijo91** [comment]
@nmldiegues ready to be merged?

**Comment by pedrorijo91** [comment]
Just pushed a commit with a new configuration: [withHistory](http://pitest.org/quickstart/maven/#mutationcoverage-goal), which allows faster analysis by reusing previous analysis results. For now this will only help while running locally since the file system is clean in every run, but for projects where we are using a controlled CI we may adapt it to improve speed.

See: https://github.com/hcoles/pitest/blob/b8e826a34227f804f8c85363a20505196f69de01/pitest-maven/src/main/java/org/pitest/maven/AbstractPitMojo.java#L111

Edit: I think we may be able to hack travis into keeping the pit history file between builds: https://docs.travis-ci.com/user/caching/#arbitrary-directories

**Review by nmldiegues — APPROVED** [review]
Thanks for following up on the comments!

**Pull request merged**
